Fix formatting of s04/2
rockkid777/pti-msc-2015-zv pull request #19
Opened 2017-06-17 18:53 UTC by varjujan

2017-06-17 21:24 UTC, varjujan commented on s04/1.md
> +## Párhuzamos és elosztott rendszerek szemantikai leírása lehetséges formái
Ez a rész eléggé rövid, de egy korábbi kidolgozásban azt írták, ez már csak mese szinten kell. Ha valaki szeretné, kiegészítheti, én már nem tervezem.

2017-06-19 22:18 UTC, balintkissdev requested changes
Így késő este átolvastam ahogy tudtam, ne haragudj a két napos késésért. Adtam feedback-et. Egész szép munka.

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +S4/1. Párhuzamos folyamatok modellezése Petri hálók segítségével. Petri hálók definíciója és működési szabálya.
Ide lehetne egy fejléc és tartalomjegyzék ilyem módon hogy átláthatóbb legyen:

# S04-1 Párhuzamos folyamatok modellezése Petri hálók segítségével
1. Petri hálók definíciója és működési szabálya
2. Párhuzamos folyamatok legfontosabb viselkedési tulajdonságai (elevenség, biztonságosság, korlátosság) és azok vizsgálatára szolgáló eszközök (elérési, fedési fa).
3. Petri doboz alkalmazása párhuzamos folyamatok modelljének felépítésében.
4. Párhuzamos és elosztott rendszerek szemantikai leírása lehetséges formáinak (műveleti, leíró, axiomatikus) bemutatása egy konkrét példán keresztül.

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +1. t aktivizálható, ha $\forall$p $\in$ $\bullet$t: M(p) $\ge$ v(p, t).
Informálisan el tudod magyarázni szóban ezeket a részeket?

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +* $L_0$ szinten (holt): $\forall$$\varsigma$ $\in$ L(N, $M_0$) : t $\not\in$ $\varsigma$
Magyarázatok:

L_0: Nem lehet egyszer se végrehajtani átmenetet
L_1: Van végrehajtás (L_0 tagadása ugyanezt adja)
L_2: Minden korlátnál többször végre tudom hajtani
L_3: Van egy darab végrehajtás, ezt akárhányszor végre tudom hajtani
L_4: Minden elérhető állapotra az átmenetek L_1 szinten elevenek legyenek

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +$\Sigma$ = (S, T, W, $\lambda$, M), ahol S a helyek, T az átmenetek halmaza, W az éleket leíró reláció, $\lambda$ a
Formázás:

$\Sigma$ = (S, T, W, $\lambda$, M), ahol

* *S* a helyek
* *T* az átmenetek halmaza
* *W* az éleket leíró reláció
* $\lambda$ a címkefüggvény
* *M* pedig a súlyozás.

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +## Párhuzamos és elosztott rendszerek szemantikai leírása lehetséges formái
"Párhuzamos és elosztott rendszerek szemantikai leírásának lehetséges formái"

2017-06-19 22:18 UTC, balintkissdev commented on s04/1.md
> +## Alapfogalmak
Látom ez az előző kidolgozásban volt. Ide kerüljön a tétel címszava

## Petri hálók definíciója és működési szabálya

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
> +S4/2. Többrétegű architektúra, elosztott szerveroldal. Kommunikációs eszközök: távolieljárás-hívás és üzenet alapú
# S04-2 Elosztott alkalmazások készítése
## Tartalom
1. Többrétegű architektúra, elosztott szerveroldal
2. Kommunikációs eszközök: távolieljárás-hívás és üzenet alapú infrastruktúra (point-to-point és publish-subscribe modell)
3. Névszolgáltatás
4. Enterprise JavaBeans komponensmodell, EJB-k fajtái
5. Beanek életciklusa
6. Dependency injection
7. Elosztott és globális tranzakciók

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
### Middleware szolgáltatások
* Távoli eljáráshívás 
* Szálkezelés
* Terheléskiegyenlítés
* Átlátszó hibakezelés
* Perzisztencia 
* Tranzakciókezelés 
* Objektumok életciklusa
* Aszinkron üzenetkezelés 
* Biztonság
* Resource-pooling
* Autentikáció
* Authorizáció
* Caching
* Clustering
* stb.

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
> -  - a tároló feladata, hogy nyilván tartsa a kliens-bean kapcsolatokat
nyilvántartsa

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
> +* void vagy Future visszatérési értékük kell, hogy legyen
`void` vagy `Future` visszatérési értékük kell, hogy legyen

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
> +* tranzakció: adat lekérdezések és módosítások egysége
* Tranzakció: adat lekérdezések és módosítások egysége
* *ACID* tulajdonságok
    + Atomicitás (Atomicity): vagy teljesen végrehajtódik (commit) vagy semennyire (rollback)
    + Konzisztencia (Consistency): konzisztens állapotból konzisztens állapotba vezet
    + Izoláció (Isolation): konkurens rendszerben a tranzakciók nem interferálnak
    + Tartósság (Durability): sikeres tranzakció eredménye tartós

2017-06-19 22:18 UTC, balintkiss501 commented on s04/2.md
> +* lokális tranzakció
**Lokális tranzakció**

* a transaction manager a resource manager része
* műveletek csak azon az egy erőforráson végezhetők

**Globális tranzakció**
* különálló transaction manager
* egy tranzakción belül több különálló erőforrás is használható
* a fizikailag elosztott erőforrások koordinálása a 2-fázisú commit protokoll segítéségével valósul meg
    1. fázis: minden resource managert megkérdez, hogy commitolhat-e
    2. fázis: mindegyik
        * commitol, ha az össze válasz igen volt
        * roll back, különben
* Java Transaction API segítségével valósítható meg

2017-06-20 09:42 UTC, balintkiss501 commented on s04/2.md
Nem dobod be? Ha nem is kell fejből tudni az összes felsorolást, de átfogó képet és áttekintést ad, hogy mik azok a concern-ek, amiket a J2EE alkalmazásszerver megold és nem a programozónak kell feltalálnia a kereket.

2017-06-20 19:51 UTC, balintkiss501 commented
@varjujan Légyszi szólj ha a Middleware-es kommentemmel nem értesz egyet és hogy miért, ha nem akarod, akkor elfogadhatjuk így is, legfeljebb a saját repómban beleírom.

2017-06-20 21:11 UTC, varjujan commented on s04/2.md
Bocsi, holnap megcsinálom, csak ma nem értem rá

2017-06-21 10:04 UTC, balintkiss501 commented on s04/2.md
Nyugodtan, semmi gond, köszi a visszajelzést.

2017-06-21 11:46 UTC, balintkissdev approved these changes

2017-06-21 13:22 UTC, merged