Initial commit of s04-3
rockkid777/pti-msc-2015-zv pull request #2
Opened 2017-06-13 09:44 UTC by balintkiss501

2017-06-14 17:31 UTC, dobreffandras requested changes
Alapvetően jól megszerkesztett. Szép munka 👍 

- A TODO-kat még csináld meg.
- Illetve írtam 1-2 kommentet.

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +&nbsp;`new HelloThread()).start()`
typo

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
typo

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +
Ide be lehetne rakni a [szálak.ppt](http://kto.web.elte.hu/hu/oktatas/eak2/szalak.ppt) 35. diáján látható képet a jobb átláthatóság érdekében.

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* Természetesen nem csak metódusokra implikálható, szinkronizációs blokkot is hozhatunk látre, melynek belsejében
typo (látre)

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* Final mezőknél plusz garanciákat ad a memória modell: garantáltan inicializálva lesznek, mikor a konstruktor
Itt nem is igazán az inicializálás a lényeg talán, hanem a nyilvánosságra hozás. Tehát, hogy más szálak számára is látható lesz az érték. Ha nincs igazam, kérlek cáfolj meg.

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +        * és $ hb(w, r) $
Ez itt nem volt teljesen világos. A `w.v` meg az `r.v` mit is akar kifejezni pontosan? 
Tehát, hogy nincs olyan írás (`w`), melyet követő olvasás által látható írások előbb történnének, mint `w`?
Illetve ez nem jelenik meg jól GitHub-on, szerintem a *-ok előtti space-ek nem jók. Feljebb jó volt a [217-es sorban](https://github.com/rockkid777/pti-msc-2015-zv/pull/2/files#diff-7f624f5f8c6d6bee4381394cdde5f354R217)

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* A két művelet több lépésből állnak, ezek a lépések pedig összefolynak
ez nem sikerült magyarra :)

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* *Read-modify-write* és *Check-then-act* utasítások atomikusan hajtódnak végre
Mi az a _read-modify-write_? Csak itt van megemlítve. Szinonima a _chek-then-act_-re?

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* Hatékony abban az esetben ha sok az olvasás és írás művelet rajtuk.
Ha jól tudom akkor hatékony, ha az olvasások vannak túlnyomó többségben, és relatív kevés az írás.

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* Alap implemetációja a CyclicBarrier, mely a kontruktorában megadott számú szálat vár be.
typo (kontruktorában)

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +* Túl nagy feladatok: kismértékű konkurrencia
konkurencia helyett párhuzamosíthatóságot írnék.

2017-06-14 17:31 UTC, dobreffandras commented on s04/3.md
> +  folyamatok futását.
Ez a bekezdés jó bevezetőnek, de a Priority inversion jelentése:
"ha egy alacsonyabb prioritású folyamat implicit megelőz egy magasabb prioritású folyamatot"

2017-06-14 19:56 UTC, balintkiss501 commented
Köszi @dobreffandras , holnap ha hazaérek megnézem jobban a kommentjeidet.

Közben saját gépemen legeneráltam pandoc-al PDF kimenetet és úgy javítottam a formázást és bekezdéseket, hogy pandoc jól tudjon generálni. Arra kérek további review-kor, hogy a pandoc kimenetet ellenőrizzétek ezzel a paranccsal:

pandoc 3.md -o 3.pdf

2017-06-14 20:05 UTC, balintkiss501 commented
Akarom mondani a kommenteken sok tennivaló nincs, inkább a TODO-k megcsinálása.

2017-06-15 18:36 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new HelloThread()).start()`
Bocsi nem látom, le tudod írni mi az?

2017-06-15 18:38 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
Itt se látom a hibát, de át tudom fogalmazni:

Adhatunk `Thread` konstruktorába egy `Runnable` interfészt megvalósító osztályt

2017-06-15 18:50 UTC, balintkiss501 commented on s04/3.md
> +* Final mezőknél plusz garanciákat ad a memória modell: garantáltan inicializálva lesznek, mikor a konstruktor
Inkább akkor így lehetne átfogalmazni:

"Java memória modell kimondja, hogy konstruktor befejezésekor a final mezők garantáltan inicializálva lesznek"

2017-06-15 18:51 UTC, balintkiss501 commented on s04/3.md
> +* Final mezőknél plusz garanciákat ad a memória modell: garantáltan inicializálva lesznek, mikor a konstruktor
A "biztonságosan jött létre, azaz nem szökött ki a this referencia a konstruálódása során" pedig ott volt előbb, de az a memória modell-től független.

2017-06-15 19:06 UTC, balintkiss501 commented on s04/3.md
> +        * és $ hb(w, r) $
v a változót jelenti. Igazából jó is hogy szólsz, az angol JVM specifikációból másoltam és csak belekavarodtam amikor újra próbáltam megérteni.

https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.4.5
"A set of actions A is happens-before consistent if for all reads r in A, where W(r) is the write action seen by r, it is not the case that either hb(r, W(r)) or that there exists a write w in A such that w.v = r.v and hb(W(r), w) and hb(w, r)."

Tudsz segíteni hogy lehetne jobb?

### Happens-before konzisztencia

* Legyen
    + $A$: műveletek halmaza
    + $r$: olvasások $A$-ban
    + $w$: írási műveletek $A$-ban
    + $v$: változó amit $r$ olvas és $w$ ír
    + $W(r)$: írási műveletek, amiket $r$ lát

* Happens-before konzisztens $A$ műveletek halmazában minden egyes $r$ olvasás olyan $w$ írást lát

      $\Longrightarrow$ ami olvasásnak megengedett, hogy happens-before sorrendben lássa

* Nem létezik olyan, hogy $hb(r, W(r))$

      $\Longrightarrow$ olvasások happens-before relációban vannak az írásokkal amiket az olvasások
      látnak

* Vagy pedig létezik $w$ írás $A$-ban, amiben
    + $w.v = r.v$   ($w$ által írt és $r$ által olvasott $v$ változó értéke megegyezik)
    + $hb(W(r), w)$ ($r$ általá látott $W(r)$ írások $w$ előtt vannak)
    + $hb(w, r)$    ($w$ írás $r$ olvasás előtt történik)

2017-06-15 19:07 UTC, balintkiss501 commented on s04/3.md
> +* A két művelet több lépésből állnak, ezek a lépések pedig összefolynak
"Egy-egy művelet több lépésből áll, ezek a lépések pedig összefolynak" jó lesz?

2017-06-15 19:20 UTC, balintkiss501 commented on s04/3.md
> +* *Read-modify-write* és *Check-then-act* utasítások atomikusan hajtódnak végre
Eredetileg a Java Concurrency in Practice könyvből olvastam, de megtaláltam rá a magyarázatot neten is: http://brevitaz.com/race-condition-java-concurrency-2/

Így tudom elmagyarázni:

### Read-modify-write
* Egy értéket változóból kiolvas (*read*), módosítja az értéket (*modify*), majd visszaírja a változóba (*write*)
* Nem atomi művelet: a három esemény közötti időben megváltozhat a változó amiből az érték lett kiolvasva.
* Tipikus példája ennek a post-increment (`i++`)
    + `i` értékének kiolvasása, másolat készítése az értékből
    + magának az érték növelése eggyel
    + érték visszaírása `i`-be

### Check-then-act
* Egy állapotot megvizsgál (*check*), majd azalapján cselekszik egy szál (*act*)
* Nem atomi művelet: a két esemény közötti időben megváltozhat az eredetileg megvizsgált állapot.
* Másik megfogalmazás: Teendő elvégzéséhez (*act*) olyan megfigyelést (*check*) vesz alapul, ami valószínűleg elavult
  adatra épül

2017-06-15 19:24 UTC, balintkiss501 commented on s04/3.md
> +* Hatékony abban az esetben ha sok az olvasás és írás művelet rajtuk.
Igazad van.
https://stackoverflow.com/questions/17853112/in-what-situations-is-the-copyonwritearraylist-suitable

* Másolat készítése drága $\Longrightarrow$ akkor hatékony, ha több az olvasás mint az írás

2017-06-15 19:30 UTC, balintkiss501 commented on s04/3.md
> +  folyamatok futását.
Tényleg, én marha kihagytam a jelentést.

* A fontosabb feladatok elvégzésése érdekében prioritást rendelhetünk a szálakhoz.
* Ha egy magasabb proritású folyamat futtathatóvá válik, akkor a rendszer késlelteti az alacsonyabb prioritású
  folyamatok futását.
* Priority inversion: ha egy alacsonyabb prioritású folyamat implicit megelőz egy magasabb prioritású folyamatot

2017-06-15 20:06 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
"konstruktorának"?

2017-06-16 07:55 UTC, balintkiss501 commented on s04/3.md
> +        * és $ hb(w, r) $
Ha nincs ötleted, akkor ezt a részt ki is lehetne hagyni, ez nem volt Kozsik anyagában és az előző tételkidolgozásokban.

2017-06-16 12:18 UTC, dobreffandras commented on s04/3.md
> +&nbsp;`new HelloThread()).start()`
A zárójelekre gondoltam.

2017-06-16 12:19 UTC, dobreffandras commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
Itt is a zárójelek :)

2017-06-16 12:50 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new HelloThread()).start()`
Már látom, köszi.

2017-06-16 12:50 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
Köszi.

2017-06-16 14:00 UTC, dobreffandras commented on s04/3.md
> +        * és $ hb(w, r) $
Aha, alakul :D

- Nem létezik olyan, hogy 
  - $hb(r, W(r))$
     $\Longrightarrow$ olvasások happens-before relációban vannak az írásokkal amiket az olvasások
látnak
  - van $w$ írás $A$-ban, amiben
    + $w.v = r.v$ ($w$ által írt és $r$ által olvasott $v$ változó értéke megegyezik)
    + $hb(W(r), w)$ ($r$ általá látott $W(r)$ írások $w$ előtt vannak)
    + $hb(w, r)$ ($w$ írás $r$ olvasás előtt történik)

[Magyarul: 1) minden olvasás látja az azt megelőző írásokat. 2) Ha írunk egy $v$ változót, azt az olvasó folyamatnak mindenképp látnia kell]

2017-06-16 17:55 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new HelloThread()).start()`
Javítva.

2017-06-16 17:56 UTC, balintkiss501 commented on s04/3.md
> +&nbsp;`new Thread(new HelloRunnable())).start()`
Javítva.

2017-06-16 17:56 UTC, balintkiss501 commented on s04/3.md
> +
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* Természetesen nem csak metódusokra implikálható, szinkronizációs blokkot is hozhatunk látre, melynek belsejében
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* Final mezőknél plusz garanciákat ad a memória modell: garantáltan inicializálva lesznek, mikor a konstruktor
Javítva a fogalmazás.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +        * és $ hb(w, r) $
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* A két művelet több lépésből állnak, ezek a lépések pedig összefolynak
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* *Read-modify-write* és *Check-then-act* utasítások atomikusan hajtódnak végre
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* Hatékony abban az esetben ha sok az olvasás és írás művelet rajtuk.
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* Alap implemetációja a CyclicBarrier, mely a kontruktorában megadott számú szálat vár be.
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +* Túl nagy feladatok: kismértékű konkurrencia
Javítva.

2017-06-16 17:59 UTC, balintkiss501 commented on s04/3.md
> +  folyamatok futását.
Javítva.

2017-06-17 08:56 UTC, dobreffandras commented
Pöpec lett 🥇

2017-06-17 08:56 UTC, merged