Initial commit of s02-1
rockkid777/pti-msc-2015-zv pull request #33
Opened 2017-06-22 00:55 UTC by balintkiss501

Closes #3

2017-06-22 09:36 UTC, varjujan requested changes

2017-06-22 09:36 UTC, varjujan commented on s02/1.md
> +    + Imperatív nyelvek: **HOGYAN** csinálja meg a feladatot a program, utasítások írása, sokszor memóriát
"sokszor a memóriát"

2017-06-22 09:36 UTC, varjujan commented on s02/1.md
> +1. Közel áll, hogy mi a feladat, mi a feladat leírása
"Közelebb áll a feladat és annak leírása" - ha ilyesmire gondoltál itt, akkor ez a megfogalmazás talán egyértelműbb.

2017-06-22 09:36 UTC, varjujan commented on s02/1.md
> +* *Reverse*: **NEM FORDÍTJA MEG A MEGÉLVŐ LISTÁT!** Másolatot készít, ami meg van fordítva.
"MEGLÉVŐ"

2017-06-22 09:36 UTC, varjujan commented on s02/1.md
> +* *Szigorú típusosság*
A szigorú típusosságtól kezdve a felsorolt tulajdonságok szerintem már nem a Tisztasághoz tartoznak közvetlenül, lehet célszerűbb lenne szétszórni ezeket más vázlatpontoknál, esetleg csinálni egy külön "Egyéb tulajdonságok" részt.

2017-06-22 09:36 UTC, varjujan commented on s02/1.md
> +* Mintha interaktívan programoznánk
Nem "imperatívan" akart lenni?

2017-06-22 09:52 UTC, balintkiss501 commented on s02/1.md
> +* Mintha interaktívan programoznánk
De igen.

2017-06-22 21:52 UTC, varjujan approved these changes

2017-06-23 08:08 UTC, balintkiss501 commented
@rockkid777 , @dobreffandras , van hozzáfűznivalótok?

2017-06-23 08:18 UTC, rockkid777 commented
@balintkiss501 nekem csak annyi, hogy md-ben a header-ekre alapból tudsz hivatkozni, de ez apró formai dolog, ezen ne álljunk le, max egy későbbi iterációban.
Tartalmilag nem tudom most tüzetesebben átnézni, szerintem megbízhatunk egymásban annyira, hogy egy kontribútor approve-ja döntő legyen. Ha mégis valaki később kivetnivalót talál, szabadon nyithat issue-t, és dolgozhat rajta. 🙂 
Egyébként jól néz ki, a monádoknál talán szükséges lehet a reader, writer monád, meg talán 1-2 szó a lift-ről, de lehet, hogy ez már túl részletes lenne. Érdemes lehet rákérdezni esetleg Ambrusnál. Nagyon jól összeszedett, szép kidolgozás! 👍

2017-06-23 09:24 UTC, balintkiss501 commented
@rockkid777 

* Módosítom még a README-t, csak munkaidőben nem akarok ezzel időzni. 
* Reader/Writer tényleg túl részletes lenne, elég tudni csak nagyjából mit csinálnak
* lift az már Funkcionális nyelvek 2-höz tartozik, de megnézem Páli Funkcnyelvek 1 előadását hogy volt-e róla szó vagy sem

2017-06-23 09:26 UTC, rockkid777 commented
@balintkiss501 jogos, az csak funkcnyelvek 2, és haskell specifikus. Ez esetben részemről teljesen rendben van.

2017-06-23 09:27 UTC, rockkid777 approved these changes

2017-06-23 10:01 UTC, dobreffandras requested changes

2017-06-23 10:01 UTC, dobreffandras commented on s02/1.md
> +    + Minteillesztés + rekurzió: mint a teljes indukció matematikában
typo "Mintaillesztés"

2017-06-23 10:01 UTC, dobreffandras commented on s02/1.md
> +* Haskell-ban és Clean-ben: alfüggvény/paraméter `!`-el való megjelölése
Mármint ezzel érhetjük el azt, hogy a kiértékelés mohó legyen, mert alapvetően lusta, ugye? Szerintem ezt itt érdemes lenne tisztázni.

2017-06-23 10:01 UTC, dobreffandras commented on s02/1.md
> +foldr :: (.a -> .(.b -> .b)) .b ![.a] -> .b)
Itt a pöttyök mit is jelentenek? (Esetleg magyarázat arra, hogy a listát mért kell mohón kiértékelni?)

2017-06-23 10:01 UTC, dobreffandras commented on s02/1.md
> +    + Argumentum: milyen típusú értékek leygenek a listában és milyen típusú értéket ragasszon össze `Cons`
type "legyenek"

2017-06-23 12:23 UTC, balintkiss501 commented on s02/1.md
> +* Haskell-ban és Clean-ben: alfüggvény/paraméter `!`-el való megjelölése
Igazad van. Alapértelmezés lusta, leírom a "lusta" részhez

2017-06-23 12:24 UTC, balintkiss501 commented on s02/1.md
> +foldr :: (.a -> .(.b -> .b)) .b ![.a] -> .b)
Megfogtál. Nem tudom, mert Clean-es szintaxis. Inkább a Haskell definíciót írom le, azt könnyebb megtanulni.

2017-06-23 19:50 UTC, farkasdav93 commented on s02/1.md
> +* *Head*: lista elemének olvasása
*lista első elemének olvasása

2017-06-23 20:12 UTC, balintkiss501 commented on s02/1.md
> +* *Head*: lista elemének olvasása
Köszi.

2017-06-23 20:21 UTC, farkasdav93 commented on s02/1.md
> +* `data Tree = Leaf | Node a (Tree a) (Tree a)`
data Tree a = ...

2017-06-24 11:24 UTC, dobreffandras approved these changes

2017-06-24 11:34 UTC, merged