S00-1 Szintézis és verifikáció (Programozás elmélet)
rockkid777/pti-msc-2015-zv pull request #36
Opened 2017-06-22 20:51 UTC by dobreffandras

2017-06-23 06:53 UTC, varjujan commented
Átolvassam, vagy még tervezel módosítani rajta?

2017-06-23 09:07 UTC, dobreffandras commented
nem terveztem módosítani csak, amit kiszúrtok :)

2017-06-23 09:20 UTC, balintkiss501 commented
@dobreffandras Rendelj reviewer-t, legyen kicsit formalizáltabb.

2017-06-23 10:36 UTC, dobreffandras commented
Akkor a #37  alapján s00 mappában az 1.md file lesz ez a tétel

2017-06-23 18:17 UTC, varjujan requested changes

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +    D_f & = \{\{n,d,l\} \in A \ | \ d \neq 0 \} \\
A 'd' helyett nem az 'n'-nek nem szabad, hogy 0 legyen?

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +Itt a $Q : A \rightarrow \mathbb{L}$ egy állítás, aminek az igazsághalmaza: $[Q] := \{q \in Q \ | \ Q(a) \ igaz \}$. Tehát
Itt leírhatnád, hogy a "[ ]" jelölést magyarázod (már ha nem én értem félre). Elsőre nem esett le, hogy honnan jön az a Q.

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +amelyekről azt kell eldönteni, hogy terminálnak-e (hibátlan véges hosszú) és végállapotuk a feladat által megkívánt
"hibátlan és véges hosszú"

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +\text{if } \pi_1 \rightarrow S_1 , ... , \pi_n \rightarrow S_n \text{ fi} & = \\
Hiányzik a függvény argumentuma:
(if ... fi)(\sigma) = ...

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +1. Amíg $\pi$ teljesül, addig szekvenciálisan összefűzzük az $S_0$-t a "rekurzívan" hívott ciklussal újra
A sor végén az "újra" szerintem felesleges

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +    (u;\text{parbegin } S_1 \lVert ... \lVert S_{i-1} \lVert T_{i} \lVert S_{i+1} \lVert ... \lVert S_n \text{ parend})(\sigma) & \quad \text{ha } \text{skip} \neq S_i = u;S_i \\
Az utolsó S_i helyett T_i kellene legyen

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +    (a komponens programok számára kijelöj egy-egy olyan feladatot. Ha a komponens programok egyenként megoldják saját
Milyen feladatot jelöl ki?

2017-06-23 18:17 UTC, varjujan commented on s00/1.md
> +vizsgálatához ez elegendő is. a teljes helyességhez a holtpont-mentességet is vizsgálni kell majd.
Pont helyett vessző, vagy 'a' helyett 'A'

2017-06-24 10:21 UTC, balintkiss501 commented on s00/1.md
> +A program alap-állapottere az **program interfésze**, mellyel a program a környezetével kommunikál (kezdőállapotát
"A program alap-állapottere a"

2017-06-24 10:30 UTC, balintkissdev requested changes
Igazából jó lesz. Nyílván mi ketten máshogy tanulunk, mert én szeretem bullet-point-okba szedni a mondatokat és gondolatokat, valamint a formális képletekhez informális laikus magyarázatot adni ha lehet. Ezt majd megcsinálom a saját személyes fork-omban.

Csak egy helyesírási és egy Markdown hibát találtam.

2017-06-24 10:30 UTC, balintkiss501 commented on s00/1.md
> +A program alap-állapottere az **program interfésze**, mellyel a program a környezetével kommunikál (kezdőállapotát
"A program alap-állapottere a"

2017-06-24 10:30 UTC, balintkiss501 commented on s00/1.md
> +A várakozó utasítás ($\text{await }\beta\text{ then } S \text{ ta}$) szemantikájánál láttuk, hogy 3 eset lehetséges:
pandoc-ban szétcsúszott a formázás. A kezdőmondat és a felsorolás között hagyj ki egy üres sort.

2017-06-24 11:26 UTC, dobreffandras commented
@balintkiss501  ha valahol nem elegendő az informális magyarázat, akkor azt jelezd nyugodtan.

2017-06-24 11:36 UTC, dobreffandras commented on s00/1.md
> +    D_f & = \{\{n,d,l\} \in A \ | \ d \neq 0 \} \\
Na ezt sose tudtam megjegyezni. Szóval elvileg d|n jelentése: "d osztója n-nek". Ezek szerint pont fordítva írtam. Ha a szövegben felcserélem, akkor már jónak kell lennie.

2017-06-24 11:57 UTC, dobreffandras commented on s00/1.md
> +A várakozó utasítás ($\text{await }\beta\text{ then } S \text{ ta}$) szemantikájánál láttuk, hogy 3 eset lehetséges:
Elvileg már jó.

2017-06-24 12:01 UTC, balintkiss501 commented on s00/1.md
> +A várakozó utasítás ($\text{await }\beta\text{ then } S \text{ ta}$) szemantikájánál láttuk, hogy 3 eset lehetséges:
Jó lett, kösz.

2017-06-24 12:02 UTC, balintkissdev approved these changes
Én elfogadom. Ha bármi informális magyarázat eszembe jut a formális cuccokhoz, akkor gyűjtöm magamnak és csinálok egy új pull request-et. Most egyelőre viszont le vagyok terhelve Formális szemantika tárggyal.

2017-06-24 12:15 UTC, varjujan approved these changes

2017-06-24 12:40 UTC, merged