S01-5 - Projektirányítás az informatikában
rockkid777/pti-msc-2015-zv pull request #40
Opened 2017-06-24 13:09 UTC by dobreffandras

Closes #25

2017-06-24 15:05 UTC, varjujan requested changes
Huhh, hát tényleg rengeteg olyasmit kér a tétel, amit szerintem még az se tud/használ, akinek ez a feladata. Ha nem bánod, valamelyik nap készítenék ebből egy rövidített verziót. Elsőre mindig jó egy hosszabb verziót olvasni, de én pl. nem tudok ilyen hosszú anyagból tanulni.
(Ha meg bármelyik vizsgáztató be meri nyögni, hogy soroljam már fel neki Geert Hofstede dimenzióit, biztosan ráborítom az asztalt.)

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +* az informatikai ipar érzékeny a gazdasági helyzet, mert ha nem megy a gazdaság, akkor a gazdálkodó szervek
"helyzetre"

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +    _Előnyök_: gyors döntés, rugalmasság, csapatmunka, kreativitás
pandoc-kal generált pdf-ben az Előnyök/Hátrányok rosszul jelennek meg nálam. Alá akartad húzni ezeket? Ha igen, nálam azt hiszem 2 db '_' kellett elé és mögé is.

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +![Funkcionális szervezet](img/funkcionalis_szervezet.png)
Ez a kép és a projekt csapat képe már a 4. pontnál jelenik meg pdf-ben, az egész oldal szét van csúszva kicsit. Talán ha kisebbre vennéd egy kicsit a képméreteket, jó lenne.

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +| Status quo megőrzése | ROI           | Egyéni túlélés   | Külső és belső vállalatpolitika | Csodák |
Szintén összefolynak kicsit a dolgok, talán sima felsorolásként átláthatóbb lenne. (Vagy elég maga a kép róla)

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +**Méret**: 3-5 fő
Az elcsúszott képek miatt ez a rész nem is látszik.

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +* vagy a cél telesülése előtt különböző okokból:
"teljesülése"

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +* **MIT** kell csinálni?
Hiányzik egy sortörés, így nem felsorolás.

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +**Időjáték**: egy tevékenységet mennyivel lehet késleltetni anékül, hogybármely közvetlenül követő másik
"anélkül", "hogy bármely, közvetlenül őt követő"

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +tevékenység legkorábbi kezdése kését szenvedne.
"késést"

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +A kritikus útat azok a tevékenységek határozzák, melyek teljes időjátéka nulla.
"A kritikus utat azok a tevékenységek határozzák meg"

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +A kritikus lánc hasonló a kritikus úthoz, de az erőforrások is figyelembe vannak véve.
Erről tudnál még írni 1-2 gondolatot? (Nekem) ebből nem teljesen egyértelmű, mi is akar ez lenni.
Az én vizsgajegyzetemben ezek szerepelnek:
* kritikus lánc: leghosszabb út, ahol a kritikus erőforrásokat használjuk
* lényege: nehezen megkapható erőforrások minél jobban ki legyenek használva
* biztonsági puffer: tartalék idő a kritikus erőforrások előtt

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +A követelménykezelés annak meghatározása, hogy a projekt mit hoz létre, a projekt terjedelme.
"a projekt terjedelme" rész nem passzol egészen a mondatba. ("mekkora a projekt terjedelme." maybe?)

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +    (nyitottak az újakra, beilleszkedés - zárkózottság, titkolózás , több és is kellhet a beilleszkedéshez)
"több és is kellhet a beilleszkedéshez" nem hiányzik ebből valami?

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +* Projekttagok
duplikátum?

2017-06-24 15:05 UTC, varjujan commented on s01/5.md
> +Az ösztönzésre meglehetősen sek elmélet és modell létezik. Az ösztönzés folyamata, egy folytonos, körkörös folyamat
"sok"

2017-06-24 15:52 UTC, dobreffandras commented on s01/5.md
> +    _Előnyök_: gyors döntés, rugalmasság, csapatmunka, kreativitás
A behúzás volt a gond. A bullet point alatt akartam behúzást, és ehhez a képet is be kellett húzni.

2017-06-24 15:53 UTC, dobreffandras commented on s01/5.md
> +    (nyitottak az újakra, beilleszkedés - zárkózottság, titkolózás , több és is kellhet a beilleszkedéshez)
:D :D Ez vicces volt :D

2017-06-24 15:54 UTC, dobreffandras commented on s01/5.md
> +* Projekttagok
Jó kérdés, így volt a diasorban :/

2017-06-24 15:56 UTC, dobreffandras commented
Egyetértek, valóban hosszúra sikeredett. Csak hát, elég sok mindenről kell beszélni, én meg úgy vagyok vele, hogy ha valamiről beszél az ember, akkor nem árt, ha az ahhoz kapcsolódó dolgokat is tudja.

2017-06-24 17:25 UTC, varjujan commented on s01/5.md
> +![A kapcsolat hőfoka](img/ugyfelkapcsolat_hofoka.png){ width=450 }
Nálam most ez lóg le félig a lapról. 
_(Megjegyzés: sok értelmét nem látom ennek az ábrának, elég jól le van írva a kapcsolat szakaszainak hangulata)_

2017-06-24 19:05 UTC, dobreffandras commented
Sehogy se jók ezek a kép méretek. Ami jó PDF-ben az nem jó mardownban és fordítva....

2017-06-25 09:15 UTC, varjujan approved these changes

2017-06-25 09:15 UTC, varjujan commented on s01/5.md
> +![Időterv kiindulás](img/idoterv1.png){ width="350px" }
PDF-ben mindegyik időterves képnek ugyanaz a képaláírása. ("Időterv kiindulás")

2017-06-25 09:52 UTC, balintkiss501 commented on s01/5.md
> +Gazdasági szempontból egy vállalatot a SWOT (Strengths-Weaknesses-Opportunities-Threats) analízis segítségével lehet
Jó a példák.:)

2017-06-25 09:55 UTC, balintkiss501 commented on s01/5.md
> +* Arisztokrácia - ROI
Ezt elsőre nem tudtam, írd oda mellé zárójelbe hogy "Return On Investment"

2017-06-25 10:08 UTC, balintkiss501 commented on s01/5.md
> +
pandoc-ban szétfolyik a következő szekció és levágja az első felét. A megoldás egy \newpage LaTeX parancs használata így:

```
### Ügyféllel való együttműködés

Az ügyfél-vállalkozó kapcsolatot különböző fázisokra tudjuk bontani.

| Fázis                                | Ügyfél szerepe                     | A kapcsolat hangulata                          |
|--------------------------------------|------------------------------------|------------------------------------------------|
| Előkészítés                          | Feladat meghatározás, tárgyalás    | bizalmatlan, aszimmetria                       |
| Szerződéskötés                       | aláírás                            | bizalmatlan, aztán felszabadult                |
| Követelményelemzés                   | interjú, visszacsatolás            | egy oldalon állnak, ügyfél kibeszélheti magát  |
| Tervezés                             | kérdésekre válasz, terve elfogadás | első megtorpanás (ügyfél fél az ismeretlentől) |
| Programozás, tesztelés, dokumetnálás | válasz kisebb kérdésekre           | béke (vihar előtti csend)                      |
| Átadás                               | átvétel                            | egymás idegeinek őrlése                        |
| Bevezetés                            | rendszer használatba vétele        | viták kora                                     |
| Garanciális időszak                  | Használat, néha panasz             | összecsiszolódás (vállalkozó kevésbé motivált) |
| Karbantartási időszak                | Használat, ritkább panasz          | belefáradnak egymásba                          |

\newpage

### Személyiségi modellek

A személyiségi modellek megpróbálják bizonyos személyiségi jegyek alapján csoportosítani az embereket. Segítenek a
csapat tagjainak kiválasztásában, motiválásában, a megfelelő kommunikáció kialakításában. Óvatosan kell azonban kezelni,
nem szabad embereket beskatulyázni, illetve vigyázni kell, mert az ilyen kategóriák önbeteljesítő tulajdonsággal
bírhatnak (egy egyén elhiszi, hogy valamelyik kategória tagja és valóban olyanná válik)
```

2017-06-25 10:10 UTC, balintkiss501 commented on s01/5.md
> +Négy féle dimenzió mentén megy a jellemzés:
"Négyféle"

2017-06-25 10:11 UTC, balintkiss501 commented on s01/5.md
> +    + Befejező: végrehajtási hibáktól való védelem, célok, határidők, múlasztások
"mulasztások"

2017-06-25 10:14 UTC, balintkissdev requested changes
Technikai apróságok.

2017-06-26 09:57 UTC, dobreffandras commented on s01/5.md
> +Gazdasági szempontból egy vállalatot a SWOT (Strengths-Weaknesses-Opportunities-Threats) analízis segítségével lehet
Nem én találtam ki, a diasorban volt :)

2017-06-26 10:04 UTC, dobreffandras commented on s01/5.md
> +
Jahj.... A képekkel is csinálta ezt.... Miért ilyen buta?

2017-06-26 11:26 UTC, balintkissdev approved these changes

2017-06-26 11:31 UTC, merged