Initial commit of s00-3
rockkid777/pti-msc-2015-zv pull request #42
Opened 2017-06-24 23:52 UTC by balintkiss501

Denotációs szemantikához még akartam magyarázatot, de már így is túl sok időt töltöttem el vele.

Bocs a késésért, Típusmodelle kidolgozása egyszerűbb lesz.

2017-06-25 14:43 UTC, varjujan requested changes

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +    + olvasható, konvencionális, hatékony kód
Így talán egyértelműbb: "olvasható, konvencionális, hatékony kód írásának módja"

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +    + Absztraktabb operációs szemantikánál
"Absztraktabb az operációs szemantikánál"

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +    + **DE!** Nem azt csinálja ami szeretnénk! Nem egyértelmű!
"amit"

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +* `"4" == 4`
Direkt ugyan az, mint az előtte lévő példa?

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +### Környezetfüggetlen grammatika**
Mit jelöl a "**"?

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +* *S*: kezdőllapoteleme *N*-nek
"kezdőállapot eleme "

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +* *p* produkciós szabály bal oldalán: *A* nem terminális áll
"nem-terminális"

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +## 5. Alapvető imperatív nyelvi elemek strukturális és természetes műveletei, illetve leíró szemantikája, hasonlóságok és különbségek <a name="chapter05"></a>
"műveleti"

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +  \mathbb{Z} \cup \{tt, ff\}$$
Itt nem inkább a [4. diasor](http://daniel-h.web.elte.hu/fs16172/lecture_04.pdf) 9/23-as diáján szereplő átmenet leírásnak kellene szerepelni?

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +& \langle \textbf{while}\ b\ \textbf{do}\ S, s \rangle \rightarrow \langle s''
Utolsó \langle felesleges

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +& \langle \textbf{while}\ b\ \textbf{do}\ S, s \rangle \rightarrow \langle s
Utolsó \langle felesleges

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +S_{ds}[\![x := a]\!] = s[x \mapsto A[\![a]\!]s] \\
A bal oldal végéről hiányzik az 's'

2017-06-25 14:43 UTC, varjujan commented on s00/3.md
> +* *F g* akkor eygenlő *g*-vel, ha *g* a fixpont
"egyenlő"

2017-06-25 14:54 UTC, balintkiss501 commented on s00/3.md
> +### Környezetfüggetlen grammatika**
Semmit, véletlen van ott, törlöm.

2017-06-25 15:02 UTC, balintkiss501 commented on s00/3.md
> +* `"4" == 4`
Jó is hogy észrevetted. Füzetemből másoltam ahogy diktálva volt, de nem tettem különbséget. Íme egy jobb változat:

* `"4" == 4` erősen típusos nyelvekben (C++, Haskell)
    + $<Exp> == <Exp>$
    + Nem szintaktikai, hanem statikus szemantikai hiba
* `"4" == 4` gyengén típusos nyelvekben (Python, JavaScript)
    + Van olyan nyelv, ami kasztolja 4-et és `true`-t ad
    + Van olyan nyelv, ami meg `false`-t
    + Statikus szemantika engedi
    + Dinamikus szemantika nem
* `"4" == "4"`
    + Java nyelvben: Java elfogadja
    + Ám nem sztringek értékét hasonlítja össze, hanem String objektum referenciákat
    + Statikus szemantika engedi
    + Dinamikus szemantika is engedi
    + **DE!** Nem azt csinálja ami szeretnénk! Nem egyértelmű!

2017-06-25 15:03 UTC, balintkiss501 commented on s00/3.md
> +* *S*: kezdőllapoteleme *N*-nek
*S*: kezdőllapot, eleme *N*-nek

2017-06-25 15:04 UTC, balintkiss501 commented on s00/3.md
> +* *p* produkciós szabály bal oldalán: *A* nem terminális áll
nemterminális

2017-06-25 15:11 UTC, balintkiss501 commented on s00/3.md
> +  \mathbb{Z} \cup \{tt, ff\}$$
Igazad van. Ez nem átmenet egyik állapotból a másikba, hanem érték kiértékelése egy állapotban. Átírom.

2017-06-25 15:40 UTC, varjujan approved these changes

2017-06-26 08:56 UTC, dobreffandras requested changes

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +    + akkor az *A.Attr* egy olyan *p* szabályban van $\rightarrow$ ahol *A* a **bal oldalon** van.
Nekem ez alapján a [jegyzet](http://www.inf.elte.hu/karunkrol/digitkonyv/Jegyzet2015/Horpacsi%20Daniel_FormalisSzemantika.pdf) alapján úgy tűnik, hogy ez itt nem következtetés, hanem egy másik megfogalmazás. Szóval az "akkor" helyett inkább "tehát", vagy "másképp" szavakat használnám.

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +* Ha *p* egy olyan $p = A \rightarrow \alpha \times \beta$ szabály
Ez itt nem egy alfa-béta direkt szorzat kéne legyen hanem alfa-X-béta (T, N, T) szimbólumsorozat. Így én nem a \times-t használnám, hanem a sima X-et. Ugye a definíció többi része is az X-re hivatkozik.

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +    + akkor az *X.Attr* egy olyan *p* szabályban van $\rightarrow$ ahol *X* a **jobb oldalon** van.
Ugyanaz, mint az előbb, az "akkor"-t lecserélném.

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +    + *x* változó értékének megadása *s* állapotban
Nekem kicsit félrevezető, mintha értékadás lenne.
Inkább: "*x* változó értéke az *s* állapotban"

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +* vagy *s[x]* minden egyéb esetben
Talán érthetőbb lenne így:

Ebből: $(s[y \rightarrow v])[x]$:

* *v*, ha *x = y*
* *s[x]*, minden egyéb esetben

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +* $\langle S_1, s \rangle \Longrightarrow ^* c$ akkor és csak akkor $\langle S_1, s \rangle \Longrightarrow ^* c$
Itt a második az S_2, S_1 helyett.

2017-06-26 08:56 UTC, dobreffandras commented on s00/3.md
> +    + Ha egy kifejezéshez két különböző jelentés is levezethető egy kifejezéshez $\Longrightarrow$ akkor azok
duplikáció

2017-06-26 15:28 UTC, balintkiss501 commented on s00/3.md
> +    + Ha egy kifejezéshez két különböző jelentés is levezethető egy kifejezéshez $\Longrightarrow$ akkor azok
http://tvtropes.org/pmwiki/pmwiki.php/Main/DepartmentOfRedundancyDepartment

Amúgy javítom

2017-06-26 16:56 UTC, dobreffandras approved these changes

2017-06-26 16:56 UTC, merged