S01-9 Szoftverfejlesztés minőségi aspektusai
rockkid777/pti-msc-2015-zv pull request #43
Opened 2017-06-25 05:59 UTC by farkasdav93

2017-06-25 15:38 UTC, varjujan requested changes

2017-06-25 15:38 UTC, varjujan commented on s01/9.md
> +**Struktúra alapú tesztelés:** tesztesetek generálása a struktúra alapján
Hiányzik egy sortörés

2017-06-25 15:38 UTC, varjujan commented on s01/9.md
> +    - Inspekció: egy dokumentumot a felülvizsgálók alaposan előkészítik és ellenőrzik a megbeszélés előtt.
"előkészítenek"

2017-06-25 15:38 UTC, varjujan commented on s01/9.md
> +valamint a kockázatokat.
Furcsán vannak tördelve a sorok

2017-06-25 15:38 UTC, varjujan commented on s01/9.md
> +Egy tesztelési eszköz, amellyel a teszt elvárt és aktuális eredményeit automatikusan össze lehet vele hasonlítani.
"vele" felesleges

2017-06-25 15:38 UTC, varjujan commented on s01/9.md
> +elágazásokat - hajt végre a teszt készlet.
"hajtja"

2017-06-25 15:49 UTC, varjujan approved these changes

2017-06-26 09:36 UTC, balintkiss501 commented on s01/9.md
> +- a különböző fejlesztési élet-ciklus modellekhez más és más tesztelés megközelítés szükséges
"Életciklus" szót egybe kell írni.

2017-06-26 09:36 UTC, balintkiss501 commented on s01/9.md
> +- minél később találunk meg egy hibát az élet-ciklusban annál költségesebb lesz annak javítása
"minél később találunk meg egy hibát az élet-ciklusban, annál költségesebb lesz annak javítása"

2017-06-26 09:40 UTC, balintkiss501 commented on s01/9.md
> +![ISO/IEC 25010:2011](img/iso_software_quality.jpg)
A kép átcsúszott a második fejezetbe pandoc-al való generálásban. Tegyél \newpage LaTeX direktívát a kép és fejezetcím közé.

```
![ISO/IEC 25010:2011](img/iso_software_quality.jpg)

\newpage

## 2. A szoftverfejlesztés és a tesztelés kapcsolata, V modell, agilitás. <a name="chapter02"></a>
```

2017-06-26 09:43 UTC, balintkiss501 commented on s01/9.md
> +![V-modell](img/v_model.png)
![V-modell](img/v_model.png)

\newpage

### 2.2 Agilitás

2017-06-26 09:46 UTC, balintkiss501 commented on s01/9.md
> +- iteratívan és inkerementálisan készül el a szoftver
Suggestion:

- iteratívan és inkerementálisan készül el a szoftver
    - iteratívan: a fejlesztési cikluson sokszor gyorsan áthaladunk, ismételjük azt
    - inkrementális: az iterációk során apránként bővítjük a rendszer funkcionalitását
- a gyorsaságra fókuszál

2017-06-26 09:48 UTC, balintkiss501 commented on s01/9.md
> +- mindig a lehető legegyszerűbb megoldás alkalmazása
Plusz pontnak ideírnám még azt is, hogy

- több metodológiája és framework-je is van, például Scrum, Kanban, XP (Extreme Programmin), RUP, stb.

2017-06-26 09:49 UTC, balintkiss501 commented on s01/9.md
> +### 3.1 Egység teszt
### 3.1 Egység teszt (Unit test)

2017-06-26 09:50 UTC, balintkiss501 commented on s01/9.md
> +### 3.2 Integrációs teszt
### 3.2 Integrációs teszt (Integration test)

2017-06-26 09:50 UTC, balintkiss501 commented on s01/9.md
> +### 3.3 Rendszerteszt
### 3.3 Rendszerteszt (System test)

2017-06-26 09:51 UTC, balintkiss501 commented on s01/9.md
> +### 3.4 Átvételi teszt
### 3.4 Átvételi tesztelés (Acceptance testing)

2017-06-26 10:02 UTC, balintkiss501 commented on s01/9.md
> +- stub-ok és driver-ek segítségével szimuláljuk az interfészt a komponensek között
Itt vallási háborúznék, a stub-ok és driver-ek leírását túlságosan leegyszerűsítettnek és félrevezetőnek találom. Nem a hívásuk határozza meg a megkülönböztethetőségüket, hanem a szerepük. Kiegészíteném.

- stub-ok és driver-ek segítségével szimuláljuk az interfészt a komponensek között
    - stub
        - "dummy" komponens
        - tesztadatot szolgál, helyettesíti a tesztelendő komponens hiányzó függőségét
        - a tesztelendő szoftverkomponensből kerül hívásra
    - driver
         - "intelligens stub"
         - programozható, "meghajtja" a tesztelendő komponenst (*benne is van a nevében, "driver"*)
        - a tesztelendő szoftverkomponenst hívja

2017-06-26 10:04 UTC, balintkiss501 commented on s01/9.md
> +- ellenőrzi, hogy az (átadás előtt álló) rendszer megfelel-e a specifikációnak
- verifikáció része

2017-06-26 10:05 UTC, balintkiss501 commented on s01/9.md
> +- ellenőrzi, hogy az (átadás előtt álló) rendszer megfelel-e a specifikációnak
Sőt, ennél jobb ez a leírás:

- ellenőrzi, hogy az (átadás előtt álló) rendszer megfelel-e a specifikációnak
    - verifikáció része

2017-06-26 10:06 UTC, balintkiss501 commented on s01/9.md
> +- célja, hogy eldöntse, megfelel-e a végtermék a megfogalmazott elvárásoknak, valamint hogy növelje a rendszerrel
- célja, hogy eldöntse, megfelel-e a végtermék a megfogalmazott elvárásoknak, valamint hogy növelje a rendszerrel szemben érzett bizalmat
    - validáció része

2017-06-26 10:07 UTC, balintkiss501 commented on s01/9.md
> +- a tevékenységek logikailag egymás után következnek, de ezek mégis átfedik egymást
+

- tesztelést úgy kell kezelni, mint külön tesztprojektet

2017-06-26 10:12 UTC, balintkiss501 commented on s01/9.md
> +A feketedoboz és fehér doboz tesztelés szinonimák a funkcionális és strukturális tesztelésre. Feketedoboz tesztelésnél
Suggestion: én ezt így tagolnám hogy minél kevesebb szöveget kelljen bevasalni

- Feketedoboz tesztelés (funkcionális tesztelés)
    - a belső felépítése a programnak rejtett a tesztelési folyamat elől

- Fehérdoboz tesztelés (strukturális tesztelés)
    - a belső struktúra ismert és az alapján alakítjuk ki a teszteseteket

2017-06-26 10:17 UTC, balintkiss501 commented on s01/9.md
> +- a használati eset diagram a rendszer egy adott szereplő általi használatának leírása
Ez egy állandó myth, hogy a "használati eset" és a "használati eset diagram" ugyanaz. Kovács Attila és Molnár Bálint tanár úr sírva fakadna, ha a kettőt összemosva mondaná valaki. "Használati eset" (Use Case) egy táblázat, mely a használati esetek leírását, lépéseit, elő- és utófeltételeit és kivételes viselkedéseit írja le. "Használati eset diagram" pedig a pálcikaemberes ábra, ami a szereplőket és használati esetek gömböceit köti össze.

Ezt expliciten meg kéne fogalmazni, különben rossz információ terjed el.

2017-06-26 10:18 UTC, balintkiss501 commented on s01/9.md
> +### 7.2 Statikus tesztelés
Meg kéne említeni a code review fogalmát.

2017-06-26 10:18 UTC, balintkiss501 commented on s01/9.md
> +#### Incidens kezelő  eszközök:
"Incidenskezelő"

2017-06-26 10:19 UTC, balintkiss501 commented on s01/9.md
> +#### Konfiguráció kezelő  eszközök:
"Konfigurációkezelő"

2017-06-26 10:20 UTC, balintkiss501 commented on s01/9.md
> +Egy eszköz, ami statikus elemzést hajt végre.
Suggestion: Itt mondanék egy példát, mint a Clang Static Analyzer, valamint pár példát hogy milyen hibákat derít fel

2017-06-26 11:24 UTC, dobreffandras approved these changes

2017-06-27 09:37 UTC, farkasdav93 commented on s01/9.md
> +### 7.2 Statikus tesztelés
itt mire gondolsz? az említett review technikák code ra is alkalmazható, nem csak a fejlesztési dokumentumokra. Kicsit szerencsétlen elnevezése van h dokumentumoknak hívja. ISQTB könyv sem tér ki külön a code review fogalmára.

2017-06-27 11:31 UTC, balintkiss501 commented on s01/9.md
> +### 7.2 Statikus tesztelés
Oké.

2017-06-27 11:43 UTC, farkasdav93 commented
Minden eddig észrevétel javítva/tisztázva, úgy h ha nincs több akkor ez merge-elhető.

2017-06-27 11:47 UTC, merged