S00-2 Típusmodellek (Programozás elmélet)
rockkid777/pti-msc-2015-zv pull request #45
Opened 2017-06-25 22:50 UTC by balintkiss501

2017-06-25 22:51 UTC, balintkiss501 commented
Tudom a fejezetcímek nincsenek rendberendezve, holnap megcsinálom. Inkább rövidebbre fogtam mint a korábbi kidolgozások, mert sietnem kell a másik tétellel, valamint máshogy volt a korábbi vizsgakidolgozásom.

2017-06-26 07:57 UTC, varjujan reviewed
Sajnos a tartalmi helyességet nem nagyon tudtam figyelni, mert már vizsgázáskor se értettem igazán mindent.
A hiányzó fejezeteket tervezed még pótolni? 11-12-13 pl.

2017-06-26 07:57 UTC, varjujan commented on s00/2.md
> +    + $S = \{ S_0, S_1, ... , S_n \}$: szort neveinek halmaza (fajták, alaptípusok)
"szortok"

2017-06-26 07:57 UTC, varjujan commented on s00/2.md
> +* Argumentum szortok (miből): $s_{i_1} \times s_{i_2} \times \cdots s_{i_k} \rightarrow s_{i_0}, k \geq 0$
Kell itt a végén az s_{i_0}? Nem csak a nyíl bal oldalán lévők az argumentumok?

2017-06-26 07:57 UTC, varjujan commented on s00/2.md
> +Mia a bijektív szignatúra algebra homomorfizmus?
"Mi a"

2017-06-26 07:57 UTC, varjujan commented on s00/2.md
> +* $B \simeq A$: *B* izomorf *A*val
"A-val"

2017-06-26 08:40 UTC, balintkiss501 commented
@varjujan Nem tervezem pótolni. Már maga a Típusmodellek vizsga is olyan volt, hogy bizonyításokat nem kérdez.

2017-06-26 12:22 UTC, dobreffandras requested changes

2017-06-26 12:22 UTC, dobreffandras commented on s00/2.md
> +* Kodern megközelítésben: azonos **SZOLGÁLTATÁST** nyújtó adatok (C++/Java/C#)
typo "Modern"

2017-06-26 12:22 UTC, dobreffandras commented on s00/2.md
> +* A $f_i$ művelet: egy $f_i: s_{i_1} \times s_{i_2} \times \cdots s_{i_k} \rightarrow s_{i_0}$ parciális leképzeés
typo "leképezés"

2017-06-26 12:22 UTC, dobreffandras commented on s00/2.md
> +* Argumentum szortok (miből): $s_{i_1} \times s_{i_2} \times \cdots s_{i_k} \rightarrow s_{i_0}, k \geq 0$
+1

2017-06-26 12:22 UTC, dobreffandras commented on s00/2.md
> +      \cdots A_{s_{i_k}} \rightarrow A_{s_{i_0}}$ parciális leképzeés
typo "leképezés"

2017-06-26 12:22 UTC, dobreffandras commented on s00/2.md
> +Mia a bijektív szignatúra algebra homomorfizmus?
Meg szerintem itt a kérdés talán túl korai. Később lesz megmagyarázva, hogy a "Szignatúra algebra izomorfizmus" az egy "bijektív szignatúra algebra homomorfizmus"

2017-06-26 16:20 UTC, balintkiss501 commented on s00/2.md
> +* Argumentum szortok (miből): $s_{i_1} \times s_{i_2} \times \cdots s_{i_k} \rightarrow s_{i_0}, k \geq 0$
Igaz.

2017-06-26 16:23 UTC, balintkiss501 commented on s00/2.md
> +Mia a bijektív szignatúra algebra homomorfizmus?
@dobreffandras , hogy írnád le? Úgy jobb ha kihagyom a kérdést?

### Szignatúra algebra izomorfizmus

* 1-1 leképezés *A* és *B* között
* Jelölés: $A \simeq B$
    + (*szürjektív: minden B-beli elemhez kapcsolódik valaki*)
    + (*injektív: minden A-beli elem különböző B-beli elemhez kapcsolódnak*)
    + (*bijektív: egyszerre szürjektív és injektív*)
* Ha egy homomorfizmus bijektív $\Longrightarrow$ akkor **izomorfizmusról** beszélünk
* Az izomorf algebrák azonosak egymással (átnevezést leszámítva)

2017-06-26 17:00 UTC, dobreffandras approved these changes

2017-06-26 18:05 UTC, balintkiss501 commented on s00/2.md
> +* A $f_i$ művelet: egy $f_i: s_{i_1} \times s_{i_2} \times \cdots s_{i_k} \rightarrow s_{i_0}$ parciális leképzeés
Bocs, kimaradt.

2017-06-26 19:23 UTC, dobreffandras commented
Végigmentem a diasoron, és le a kalappal :D
Az első verzióból úgy tűnt, hogy mintha lenne néhol hiányosság, de látva a diasort, annyi értelmet, amit lehetett azt szépen összeszedted.

2017-06-26 19:24 UTC, merged

2017-06-27 09:36 UTC, balintkiss501 commented
@dobreffandras Motivációm: nincs az az élő ember, aki a diasorokból annyi katyvaszt meg tud jegyezni, inkább csak legyen meg az elméleti háttér, hogy mi az hogy specifikáció meg homomorfizmus meg barátai.