S01-6 Szoftverfejlesztési modellek
rockkid777/pti-msc-2015-zv pull request #46
Opened 2017-06-27 12:35 UTC by farkasdav93

2017-06-27 16:44 UTC, varjujan requested changes

2017-06-27 16:44 UTC, varjujan commented on s01/6.md
> +1. Követelmények felmérése
Hiányzik egy sortörés, így PDF-ben nem felsorolás

2017-06-27 16:44 UTC, varjujan commented on s01/6.md
> +- A Gang of Four (GoF) a "Design Patterns: Elements of Reusable Object-Oriented Software” köny négy szerzője
"könyv"

2017-06-27 16:44 UTC, varjujan commented on s01/6.md
> +    Chachelésre használható például.
"Cachelésre"

2017-06-27 18:07 UTC, varjujan approved these changes

2017-06-28 18:04 UTC, dobreffandras commented
Hm... ez is érdekes tétel, mert ha nem hallott az ember ezekről a dolgokról, akkor muszáj utána olvasni, mert ez így kevés. Viszont egyesével leírni az összes mintát, anti-mintát, meg kutyafülét az nagyon sok lenne :/

Tudunk keresni valami forrást, ahol ezeknek utána lehet nézni?

2017-06-28 18:36 UTC, varjujan commented
Hát, eddig ha engem érdekelt, hogy melyik pattern miről szól, wikipédiánál nem kellett sokkal messzebb mennem. A tételben meg biztos nem kell mindet felsorolni, valószínűleg elég lenne mindegyik kategóriában egyről 4-5 mondat, meg 1-2 másikat megnevezni és körülírni 1 mondatban.

2017-06-29 11:08 UTC, farkasdav93 commented
Én nem tervezem kiegészíteni, én is ami érdekelt azt külön megnéztem, ha van konkrét javaslat hova mit rakjak még be akkor belerakom, vagy dobjatok PR-t, vagy pedig merge után nyisson rá egy újabb PR-t

2017-06-29 11:41 UTC, merged