Multiparadigma programozás és Haladó Java 2
rockkid777/pti-msc-2015-zv pull request #47
Opened 2017-06-29 10:31 UTC by farkasdav93

2017-06-29 11:21 UTC, SilverGeri commented on s02/3.md
> +    - multiset
a set-ek nem asszociatív konténerek

2017-06-29 11:24 UTC, farkasdav93 commented on s02/3.md
> +    - multiset
és ezt mivel magyarázod? a set minden referencia szerint asszociatív

2017-06-29 11:29 UTC, SilverGeri commented on s02/3.md
> +- C++ 11-től a labdákkal kiválthatók
*lambdákkal :)

2017-06-29 17:51 UTC, varjujan requested changes

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +- Nem ütközhetnek metódusai az Object és az Annotation metódusaival (felüldefiniálás-ekviv.)‏
Nálam emiatt a sor miatt nem fordult le elsőre pandoc-kal. Sajnos nem teljesen értettem a hibaüzenetet, de a "(felüldefiniálás-ekviv.)‏" rész újragépelése megoldotta. (valamelyik karakter nem tetszett neki)

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +    3. [Algoritmusok](#section01_01)
El van csúszva a section számozás

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +...
Nálam valamiért nem tetszett a pandoc-nak a "..." jelölés kód blokkon belül. Mindet törölnöm kellett, hogy rendesen forduljon.

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +- Nem ütközhetnek metódusai az Object és az Annotation metódusaival (felüldefiniálás-ekviv.)‏
Valamelyik karakterre hibát dobott a pandoc ebben a sorban. A végén a "(felüldefiniálás-ekviv.)‏" rész újragépelésével megoldódott.

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +    - Bidirectinal: előre, hátra tudunk menni, illetve írni olvasni
"Bidirectional" itt és még több helyen

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +- ha függvényekre akarjuk használni az adaptereket akkor direkbe ezt nem tudjuk megtenni, mert hiányoznak a `typedef`-ek
"direktbe"

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +        Object[] actualArgs = (args.length > 2) ? new Object[] {args[2]} : new Object[] {};
A hosszabb sorokat tördelni kellene, így kicsúszik PDF-ben

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +- hivatkozott objektum többször előfordulása esetén csak egyszer lesz elmentve
"többszöri"

2017-06-29 17:51 UTC, varjujan commented on s02/3.md
> +
Esetleg a `serialVersionUID`-t még le lehetne írni itt

2017-06-29 18:23 UTC, farkasdav93 commented on s02/3.md
> +- Nem ütközhetnek metódusai az Object és az Annotation metódusaival (felüldefiniálás-ekviv.)‏
oké, átírva tényleg megy, de továbbra is kapok egy ilyet: pandoc: Could not parse YAML header: mapping values are not allowed in this context "source" (line 18, column 14)
ez neked is előjött?

2017-06-29 18:29 UTC, varjujan commented on s02/3.md
> +- Nem ütközhetnek metódusai az Object és az Annotation metódusaival (felüldefiniálás-ekviv.)‏
Nálam azt hiszem a "..."-ok törlése javította ki

2017-06-29 18:30 UTC, farkasdav93 commented on s02/3.md
> +- Nem ütközhetnek metódusai az Object és az Annotation metódusaival (felüldefiniálás-ekviv.)‏
igen valóba, köszi

2017-06-29 18:45 UTC, dobreffandras commented on s02/3.md
> +    - multiset
Igen, habár fura, mégis az.
http://en.cppreference.com/w/cpp/concept/AssociativeContainer
És itt van egy magyarázat is:
https://stackoverflow.com/questions/25071335/why-stdset-is-an-associative-container/

2017-06-29 19:11 UTC, varjujan approved these changes

2017-06-29 19:21 UTC, dobreffandras requested changes

2017-06-29 19:21 UTC, dobreffandras commented on s02/3.md
> +    - Random access: random hozzáférést tesz lehetővé, nem csak egyesével tudunk lépkedni, írni ovlasni tudunk
typo "olvasni"

2017-06-29 19:21 UTC, dobreffandras commented on s02/3.md
> +    - Forward: előrefelé, írni olvasni
Mi a különbség itt az Input és a Forward között?

2017-06-29 19:21 UTC, dobreffandras commented on s02/3.md
> +- iterátorok invaliddá válhatnka:
typo "válhatnak"

2017-06-29 20:19 UTC, farkasdav93 commented on s02/3.md
> +    - Forward: előrefelé, írni olvasni
bocsi, felcseréltem a kettőt, meg nem volt egyértelmű a leírás, javítottam

2017-06-29 20:35 UTC, dobreffandras approved these changes

2017-06-30 05:40 UTC, merged

2017-06-30 09:12 UTC, balintkiss501 commented on s02/3.md
> +- C++ 11-től a labdákkal kiválthatók
xDDDDDDD