Típusrendszerek
rockkid777/pti-msc-2015-zv pull request #48
Opened 2017-06-29 13:16 UTC by rockkid777

Az utolsó kettőnél szándékosan hivatkoztam meg Ambrus jegyzetét, mivel ott is tömören van, a direkt másolásnak nem láttam különösebb értelmét.

2017-06-29 13:22 UTC, rockkid777 commented
A(z) #24  issue-hoz tartozik.

2017-06-29 19:24 UTC, balintkiss501 commented
@rockkid777 Rossz mappában van, nem a tudományos törzsanyag (s00) helyén. Én meg kerestem és néztem hogy mi van.

2017-06-29 19:27 UTC, dobreffandras commented
:D :D Revertelni kell az utolsó commit-ot.

2017-06-29 19:29 UTC, balintkiss501 commented
@dobreffandras Egy átmozgatást nem érzek annyira drasztikus lösung-nak. Bocs a kései reagálásért, még a rendes Ambrus-os jegyzetet is átolvasom hogy képben legyek, éjfélig megcsinálom a review-t.

2017-06-29 19:31 UTC, rockkid777 commented
@balintkiss501 köszi! Javítottam közben. 😄

2017-06-29 21:13 UTC, dobreffandras requested changes

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +operátorok. Példá- ul a természetes szám kifejezések és az ezekből és összeadásból álló kifejezések
typo "Példá- ul"

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +A szabad változókra ez nem igaz, pl. x + x 6= y + y.
itt gondolom /= vagy != akart lenni.

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +x + (num zero + x) részkifejezést az x változó hatáskörének nevezzük.
ide jó lenne egy illusztráció. Vagy LaTex-el vagy képpel (screenshot-ot szoktam).

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +ABT-kben is, pl. szeretnénk a következő egyenlőségeket.
Nem világos, hogy ez mire vonatkozik. Kimaradtak az egyenlőségek?

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +| $$ \mid let\ e\ \in x.e' $$                     |             definíció |
a \in lefordul halmazelméleti jelölésre, sima in kell

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +| $$ \mid let\ e\ \in x.e' $$                     |             definíció |
Illetve kicsit félrevezetők ezek a pipe-ok. Inkább így írnám:

A szintaxis két fajtából áll, a típusokból és a kifejezésekből.
$$ \tau, \tau', \ldots\ \in\ T_{y}\ ::=\ int \| str$$
$$ \mid e, e', \ldots \in Exp\ ::= x \| n \| "s" \| e+e \| e-e \| e \bullet e \| \|e\| \| let \ e \ in  x.e' $$

ahol

| szabály                                         |            megnevezés |
|:------------------------------------------------|----------------------:|
| int |   egész számok típusa |
| str                                          |       szövegek típusa |
| x         |               változó |
| n                                            | egész szám beágyazása |
| "s"                                          |     szöveg beágyazása |
| e+e                                          |             összeadás |
| e-e                                          |               kivonás |
| $$ \mid e \bullet e $$                          |            összefűzés |
| \|e\|                                        |                 hossz |
| $$ \mid let\ e\ in \ x.e' $$                     |             definíció |

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +$$ dom(\Gamma,x:\tau)\ := \{x\} \ cup \ dom(\Gamma) $$
typo \cup

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +$$
pdf-ben nem rakja külön sorba

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +$$
Ezt sem tördeli a pdf

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +Ez a következőképp működik: $y$-t és $z$-ta akarjuk összeadni, emiatt *y*-on végzünk rekurziót. Ha *y = zero*, akkor
typo $z$-t

2017-06-29 21:13 UTC, dobreffandras commented on s00/4.md
> +e,e',\ldots \in \ Exp ::= x | true | false | rec e_0 \ e\ e | e\ e'
typo: rec \ e_0 \ e\ e

2017-06-29 22:30 UTC, balintkissdev approved these changes
Nekem annyi bajom van inkább, hogy nincs bullet point-okba szedve a tétel, mintha a jegyzet részletei lettek volna kimásolva. Ennek ellenére összesítve van az anyag. Most már nincs sok idő, most approve-ra teszem, ha gondolod javíthatod az ajánlásaimat és észrevételeimet.

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +Hogy a típusrendszert le tudjuk írni, szükségünk van még a környezetek (context) fajtájára. Egy környezet egy
Írnék egy segédmegjegyzést, hogy

(*Analógia: a környezet olyan, mint számítógépben a memória*)

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +$$
pandoc-ban nem néznek jól a levezetési fák. Megjegyezném, hogy Ambrus jegyzetének LaTeX forrása fent van neten.

https://bitbucket.org/akaposi/tipusrendszerek/src/07740fdb50ecb7c6c6fadc84815c38ffdb327a35/jegyzet.tex?at=master&fileviewer=file-view-default

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +Ilyen például a let e in x.e', mely pl. azt fejezheti ki, hogy e'-ben az x előfordulásai e-t jelentenek
A kifejezéseket dőlt betűvel emelném ki.

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +
Tudom hogy a tematika nem írja, Ide írnám még az inverzió tételét is. A tárgy során fontos volt használni, hiszen azalapján csináltuk azt, hogy egy bonyolult kifejezésből a levezetési fában fentebb mentünk a részkifejezések típusellenőrzéséhez.

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +$$
```
$$
\begin{aligned}
  \tau, \tau',\ldots \ \in \ Ty \ &::= \ldots \,|\, \bot \,|\, \tau_1 + \tau_2 \\
  e,e',\ldots \ \in \ Exp \ &::= \ldots \,|\, \ abort^\tau\,e \,|\, {\ inj_1}^{\tau_1,\tau_2}\, e \,|\, {\ inj_2}^{\tau_1,\tau_2}\, e \,|\, \ case\,e\,x_1.e_1\,x_2.e_2
\end{aligned}
$$
```

A `&` jelek a `::=` előtt fontosak. Ellenőrizd pandoc-al.

2017-06-29 22:30 UTC, balintkiss501 commented on s00/4.md
> +$$
```
$$
\begin{aligned}
\tau, \tau', \ldots \ \in \ Ty \ &::= \ Nat \,|\, \tau_1 \rightarrow \tau_2 \\
e,e', \ldots \ \in \ exp \ &::= x \,|\, \ zero \,|\, \ suc\,e \,|\, \ rec\,e_0\,x.e_1\,e \,|\, \lambda^\tau x.e \,|\, e\,e'
\end{aligned}
$$
```

A `&` jelek a `::=` előtt fontosak. Ellenőrizd pandoc-al.

2017-06-30 06:46 UTC, rockkid777 commented on s00/4.md
> +ABT-kben is, pl. szeretnénk a következő egyenlőségeket.
A fölötte lévő példáról szól.

2017-06-30 06:59 UTC, rockkid777 commented on s00/4.md
> +$$
Igen, onnan csináltam saját konverzióval. Sajnos a MathJax alapból nem támogatja az asmath minden részét, így az infer-t sem, amit a levezetéshez használ. Találtam rá azóta megoldást, hosszabb távon át lehet írni.

2017-06-30 08:04 UTC, balintkiss501 commented
Jó lesz részemről.

2017-06-30 16:04 UTC, dobreffandras approved these changes

2017-06-30 16:04 UTC, merged