S02 2
rockkid777/pti-msc-2015-zv pull request #50
Opened 2017-06-30 22:34 UTC by balintkiss501

2017-06-30 22:35 UTC, balintkiss501 commented
Bocs nem tudtam még befejezni, de addig itt van hogy lássátok ti is és közben csinálom a befejezését amit ugyanebbe a code review-ba feltöltök.

2017-07-01 14:39 UTC, balintkiss501 commented
Na kész. Bocs, jól szétcsúztam időbeosztásilag.

2017-07-01 19:14 UTC, varjujan requested changes
Le a kalappal, szép "kis" összefoglaló. (Csak a gatyám rámegy már a nyomtatásra :D )

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +* Értékadáskor magának az érték másolása a változóba
"értéknek a másolása"

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +\newpage
Miért van itt oldaltörés?

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +    ```
Ide lehet kellene még egy sortörés, mert a következő pont címe is behúzásra kerül. Csak formai hiba.

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +Egy változó memóriacímét az `&` operátorral kérdezhetjük le, ez a referenciaoperátor.
"referenciaoperátor"-t szerintem külön kell írni.

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +    + akkor, amikor változó mérete csak futásidőben határozható meg vagy mérete stack overflow-t eredményezne
Mi van akkor?

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +    + használd ezt, ha **ha könnyű másolni**
Dupla ha

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +    + használd ezt, ha **ha könnyű másolni**
A többi "használd ezt" sorban is

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +>>>>>>> Add chapter 1, chapter 3 and chapter 5
Bent felejtett sor?

2017-07-01 19:14 UTC, varjujan commented on s02/2.md
> +* Mindkét esetben a `start()` metódust kell felüldefiniálni
run()-t kell felüldefiniálni

2017-07-01 19:40 UTC, balintkiss501 commented on s02/2.md
> +\newpage
PDF-et generálva jobban nézett ki.

2017-07-01 19:41 UTC, balintkiss501 commented on s02/2.md
> +Egy változó memóriacímét az `&` operátorral kérdezhetjük le, ez a referenciaoperátor.
Igazad van.

2017-07-01 19:41 UTC, balintkiss501 commented on s02/2.md
> +    + akkor, amikor változó mérete csak futásidőben határozható meg vagy mérete stack overflow-t eredményezne
Akkor foglalunk heap-en. Ezt odaírom.

2017-07-01 19:42 UTC, balintkiss501 commented on s02/2.md
> +>>>>>>> Add chapter 1, chapter 3 and chapter 5
Francba, merge conflict, kösz hogy szólsz.

2017-07-01 19:43 UTC, balintkiss501 commented on s02/2.md
> +* Mindkét esetben a `start()` metódust kell felüldefiniálni
Igaz.

2017-07-01 19:44 UTC, balintkiss501 commented
@varjujan 

> Le a kalappal, szép "kis" összefoglaló. (Csak a gatyám rámegy már a nyomtatásra :D )

Én ebook-olvasóra szoktam rátölteni. Azért is cicomázom a PDF generálást.

2017-07-01 19:48 UTC, balintkiss501 commented on s02/2.md
> +    + akkor, amikor változó mérete csak futásidőben határozható meg vagy mérete stack overflow-t eredményezne
*akkor foglaljunk a heap-en.

Továbbá odaírom azt is, ha polimorfizmust akarunk megvalósítani.

2017-07-01 20:00 UTC, balintkiss501 commented on s02/2.md
> +\newpage
Kiszedtem a feleslegesnek érzett \newpage-eket. Így most már egy oldallal kevesebbet kell nyomtatnod. :)

2017-07-01 21:46 UTC, varjujan approved these changes

2017-07-02 08:17 UTC, merged